name: HTML Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Requried will all actions
      - name: Checks HTML5
        uses: Cyb3r-Jak3/html5validator-action@v7.1.0
        with:
          root: .
          skip_git_check: true
